### PR TITLE
Fixed #94: Missing compatibility with API 5.6.0

### LINKED ISSUE #94: Missing compatibility with API 5.5.0?
Since Milhouse #0804 - Kodi version (18.0-ALPHA1 Git:dde9b24)  Platform: Linux x86 64-bit, DVBLink Addon doesn't start anymore (can't load shared library) ----> http://sprunge.us/QaEG .
Seems that further changes in pvr API ( https://github.com/xbmc/xbmc/pull/12609 ) caused the broken dvblink addon. Maybe some updates in the addon are required?

### PR DESCRIPTION
**Pull request by dvblogic**

### CODE REVIEW

**Comment by ksooo** [comment]
Okay, but meanwhile we're at API version 5.6.0.

**Comment by dvblogic** [comment]
Does it need any extra's from addon developer? Or we can leave this comment as is?

**Comment by ksooo** [comment]
The add-on will not compile/link/work if you do not adapt it for 5.6.0.

**Comment by ksooo** [comment]
Thanks.

**Pull request merged**
