### PR TITLE
FIXUP: c/p monster

### PR DESCRIPTION
**Pull request by koying**
/cc @ksoo

### CODE REVIEW

**Comment by ksooo** [comment]
@koing Thanks.

Could you please update the changelog and do a version bump?
https://github.com/kodi-pvr/pvr.dvblink/blob/master/pvr.dvblink/addon.xml.in
https://github.com/kodi-pvr/pvr.dvblink/blob/master/pvr.dvblink/changelog.txt

**Comment by koying** [comment]
Well, there was no bump for the commit inducing the bug. Still wants one?
Pay attention this is Jarvis, master is fine ;)

Also note that nobody could even build 2.2.0 in the current state

**Comment by ksooo** [comment]
Yeah I'm aware its Jarvis (although i accidentally posted links to master ;-)
Please update the addon version to 2.2.1 and a short changelog entry would be nice.

**Comment by koying** [comment]
Done

**Comment by koying** [comment]
Just saying, but making a dev redo his commit to bump a _build_ fix vs. a commit _that did not bump_ would be enough to discourage many ;)

**Comment by Jalle19** [comment]
@koying everyone makes mistakes. Thanks for the fix though!

**Comment by dvblogic** [comment]
@koying Thank you very much for the fix! 
Last second changes is a bad thing :(

**Pull request merged**
