### PR TITLE
pvr.dvblink v3.3.6 (Krypton)

### PR DESCRIPTION
**Pull request by dvblogic**
Fixed: PVR_TIMER.iClientIndex handling bug #58

### CODE REVIEW

**Review by ksooo — CHANGES_REQUESTED** [review]
Maybe you want to squash the two commits into one?

**Comment by dvblogic** [comment]
@ksooo  What is the good way of doing it?

**Comment by ksooo** [comment]
git rebase -i master (supposing you branched from master)
then mark the typo fix commit as "f"

**Comment by ksooo** [comment]
@dvblogic any problems with the rebase?

**Comment by dvblogic** [comment]
@ksooo This is the first time I am trying to do it and it is not really straight forward :(

**Comment by ksooo** [comment]
What's the problem exactly?

**Comment by dvblogic** [comment]
@ksooo Nothing particular. It is a lot of stuff that I do not know and have not used before. So I need to read and understand before I can make use of it.
In short, I would much appreciate if either we can leave it as is or if you can do it for me ;)

**Comment by ksooo** [comment]
@dvblogic I could cherry pick your commits, squash them and make a new PR out if it. Would that be okay for you?

**Comment by dvblogic** [comment]
@ksooo That should be fine. Thank you!

**Comment by ksooo** [comment]
superseeded by #61

**Pull request closed without merging**
