### PR TITLE
pvr.dvblink: Native Kodi timers support

### PR DESCRIPTION
**Pull request by dvblogic**
- Backport of 1.10.9 version fixes from Isengard tree
- Native Kodi series timer support
- Support for keyword-based recording timers
- added episode/season/year info to recording metadata

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you bump the major version for the addon to 2? It makes it easier for users to see which versions are for Isengard and which are for Jarvis.

**Comment by dvblogic** [comment]
@Jalle19 what would be the best way to do it? Create another pull request with updated version/history files?..

**Comment by Jalle19** [comment]
@dvblogic just edit the commit in this PR that changes the changelog, then force push.

**Comment by dvblogic** [comment]
@Jalle19 Done.
It has added empty "Merge branch 'master' of https://github.com/dvblogic/pvr.dvblink" commit, which I could not get rid of :( Hope it is ok. I am not that good with git, honestly...

**Comment by hudokkow** [comment]
It's always best to work in a branch instead of master. Much easier to control.
Anyway, closed in favour of https://github.com/kodi-pvr/pvr.dvblink/issues/31

Thanks for all the work, @dvblogic

**Pull request closed without merging**
