### PR TITLE
pvr.dvblink addon version 4.7.0

### PR DESCRIPTION
**Pull request by dvblogic**
Added: support for set/get last played position in a recording

### CODE REVIEW

**Comment by dvblogic** [comment]
@ksooo Is there any special procedure for this to be included into nightlies and release trajectory of Kodi v18? Thanks.

**Comment by MartijnKaijser** [comment]
@dvblogic you need to create a release tag on GitHub and it will be auto build and published to our repo. See existing tags

**Comment by dvblogic** [comment]
@MartijnKaijser Thanks, will do. 
In the past I had to make a pull request tp repo-binary-addons for the addon to be published. Looking through the pull requests of repo-binary-addons I assume that it is not required anymore, right?

**Comment by ksooo** [comment]
Right.

**Pull request merged**
