### PR TITLE
Native Kodi timers support and some fixes

### PR DESCRIPTION
**Pull request by hudokkow**
Superseds https://github.com/kodi-pvr/pvr.dvblink/pull/30

From the original PR description:

> - Backport of 1.10.9 version fixes from Isengard tree
> - Native Kodi series timer support
> - Support for keyword-based recording timers
> - added episode/season/year info to recording metadata

@dvblogic, please check if I didn't missed anything during cleaning and commits fixup

https://github.com/kodi-pvr/pvr.dvblink/commit/71a75d4c6d9eb8777e2ae17e08177712260bc9c1 is code format cleanup/uniformize. I can drop it if not wanted.

### CODE REVIEW

**Comment by dvblogic** [comment]
Looks good to me. Thank you very much for taking your time and effort on code formatting.

**Comment by ksooo** [comment]
We're doing translations using transifex (http://www.transifex.com). Please remove all strings.po modifications from this PR except pvr.dvblink/resources/language/resource.language.en_gb/strings.po (en_gb is Kodi default language). Other translations would be lost on next transifex import, I'm afraid.

**Comment by dvblogic** [comment]
They are English-only (gb, us, au and nz). No other languages have been touched.

**Comment by hudokkow** [comment]
@ksooo, I'll drop other translations later today. To be honest, didn't even noticed them.
@dvblogic, no effort at all. It's semi-automatic.

**Comment by hudokkow** [comment]
Dropped unwanted translations.
@ksooo, your button.

**Comment by ksooo** [comment]
@hudokkow @dvblogic thank you very much for your contribution. Much appreciated.

**Pull request merged**
