### PR TITLE
Version 4.7.1 - Added option to change default record show type

### PR DESCRIPTION
**Pull request by linknetx**
This adds an option to the TV Mosaic client to allow the default record show type to be set either to 'Record all episodes' or 'Record only new episodes' so that when adding a timer in Kodi this default is used for the 'Prevent duplicate episodes' setting. This avoids having to change the setting to your own preferences every time a new timer is set.

This also corrects 6 minor bugs within the client.cpp relating to writing the variable changes to the log file for debugging. The variable type for 'settingValue' in each case has been changed from int to bool to correct this.

### CODE REVIEW

**Comment by linknetx** [comment]
Here are images of the new setting:

image01


image02

**Comment by linknetx** [comment]
Correction:
Used class structure to interface variable 'default_rec_show_type' between client.cpp and DVBLinkClient.cpp

All commits squashed into one single commit.

**Comment by dvblogic** [comment]
@linknetx 
Can you, please, bump version (addon.xml.in file) to 4.7.1 and update change log (changelog.txt file) to include this and another (already merged) pull request?

**Comment by linknetx** [comment]
All done as requested and all commits squashed into one.

------ Original Message ------

**Pull request merged**
