### PR TITLE
Added: support for PVR_RECORDING.iChannelUid #115

### PR DESCRIPTION
**Pull request by dvblogic**

### CODE REVIEW

**Comment by ksooo** [comment]
Thank you.

**Comment by linknetx** [comment]
That's good news, many thanks.

**Comment by ksooo** [comment]
> That's good news, many thanks.

 Sure sure. I asked you several times to write this issue but at the end I did it for you. :-/

**Comment by linknetx** [comment]
> > That's good news, many thanks.
> 
> Sure sure. I asked you several times to write this issue but at the end I did it for you. :-/

Not true, I raised this on their internal ticketing system on 09-02-2019 where I usually get a faster response than on GitHub. 

09-02-2019 Ticket Received - Implementation of the Channel UID 56871

So they were probably already working on this when they received your request :-)

**Comment by linknetx** [comment]
> > That's good news, many thanks.
> 
> Sure sure. I asked you several times to write this issue but at the end I did it for you. :-/

@ksooo 

Not true, I raised this on their internal ticketing system on 09-02-2019 where I usually get a faster response than on GitHub. 

09-02-2019 Ticket Received - Implementation of the Channel UID 56871

So they were probably already working on this when they received your request :-)

In fact I also added some pictures so that they realised what the problem was:

tv recordings list
tv recordings context menu

**Comment by linknetx** [comment]
@ksooo 

capture

**Comment by ksooo** [comment]
@dvblogic don't forget addon version bump and changelog update. And after this is done and merged, don't forget to tag the new version, otherwise new addon will not show up in the addon repo (as you should know).

**Pull request merged**
