### PR TITLE
pvr.dvblink (krypton): version 3.1.0

### PR DESCRIPTION
**Pull request by dvblogic**
Fixed: Compatibility with Kodi Krypton PVR API
Added: Support for the upcoming channel logos
Fixed: Incorrect date/time presentation on Timer rules page

### CODE REVIEW

**Comment by ksooo** [comment]
To support PVR Addon API 5.1.0 (including 4.2.0 and 5.0.0 - pvr.dvblink currently is at 4.1.0 level) properly, there are some parts missing in your PR, for instance the actual API bump in addon.xml, removal of function <code>GetCurrentClientChannel</code>, support for PVR_RECORDING.channelType, PVR_RECORDING.iChannelUid.

Maybe you find this useful to get a feeling for API 5.0.0: https://github.com/ksooo/pvr.dvblink/commits/pvr-api-5-0-0 and https://github.com/kodi-pvr/pvr.vuplus/pull/40 for API 5.1.0

**Comment by dvblogic** [comment]
Can we split it into two stages at least to get pvr.dvblink buildable and working with the current Kodi Krypton nightlies?

**Comment by ksooo** [comment]
Kodi Krypton will refuse to load the addon if we merge your PR as it is now, because of an API version mismatch. Formal API bump (addon.xml) is a must. Removing GetCurrentClientChannel is a no-brainer - just remove some lines of code. Really, look at the examples I gave you. It's low effort to do it minimalistic right.

BTW, writing this text takes longer than doing the actual change. ;-)

**Comment by dvblogic** [comment]
Yep, realized this already :) Give me a sec..

**Comment by dvblogic** [comment]
Updated the pull request with PVR API 5.1.0 changes. Can you check, please, if they are ok?

**Comment by ksooo** [comment]
API changes and general code changes looking good. Cannot say anything to the dvblogic specific code changes.

**Comment by dvblogic** [comment]
Ah, just realized that there is a small, but important bug in the timeshift logic. We'll do the fix tomorrow the first thing. Please do not merge until then.

**Comment by dvblogic** [comment]
Now it's all good. Please merge the pull request. Thank you.

**Comment by ksooo** [comment]
Okay, will merge.

Please note that currently pvr.dvblink is excluded from kodi master build because it ... breaks the build. Open a PR like this https://github.com/xbmc/repo-binary-addons/issues/27 to request pvr.dvblink to be included in kodi build again.

**Comment by dvblogic** [comment]
Thanks! Can you please also merge this one:
https://github.com/kodi-pvr/pvr.dvblink/pull/44

**Pull request merged**
