### PR TITLE
pvr.dvblink (krypton) version 3.4.0

### PR DESCRIPTION
**Pull request by dvblogic**
Fixed: Crash when switching channels with timeshift enabled ( #69 )
Fixed: Hangup after period of inactivity ( #64 )
Fixed: Incorrect dvblink server version displayed in addon properties ( #66 )
Fixed: Timer Rules incorrectly detected ( #68 )
Changed: default value to "new only" when setting series recording ( #65 )
Added: timeshift commands to libdvblnikremote
Changed: dvblink channel id to string for compatibility with future dvblink versions
Added: margin of 10 seconds to IsRealTimeStream and IsTimeshifting definitions
General: code refactoring for easier maintenance

### CODE REVIEW

**Comment by dvblogic** [comment]
@ksooo Sorry for bothering. The Travis build is failing on the reasons that are outside of our competence. Do I need to care about it or this pull request can be still merged?

Further, can you please give me a hand on "tag the release and open a pull request against the Krypton branch of repo-binary-addons" on what exactly has to be done?.. Many thanks in advance.

**Comment by ksooo** [comment]
> Sorry for bothering. The Travis build is failing on the reasons that are outside of our competence. Do I need to care about it or this pull request can be still merged?

 Hmm. maybe @Jalle19 can help?

> Further, can you please give me a hand on "tag the release and open a pull request against the Krypton branch of repo-binary-addons" on what exactly has to be done?

 Use "git tag" to tag your release and open a PR against https://github.com/xbmc/repo-binary-addons where you update https://github.com/xbmc/repo-binary-addons/blob/Krypton/pvr.dvblink/pvr.dvblink.txt. Do this for both master and Krypton branch.

EDIT: You need to open a PR only for Krypton, (currently) not for master.

**Comment by ksooo** [comment]
Why do you ask first whether it is okay to merge although Travis is broken and then you merge without waiting for an answer?  :-/

**Comment by dvblogic** [comment]
I did this because Travis build for master has finished successfully for the same code. Was it a wrong assumption?

**Comment by ksooo** [comment]
Maybe, I don't know, that's why I asked @Jalle19 for help.

**Comment by dvblogic** [comment]
understood. Sorry for my impatience.

**Comment by ksooo** [comment]
You did understand what I wrote regarding the Krypton PR for repo-binary-addons? No PR no inclusion of the new version in Kodi 17.1!

**Comment by dvblogic** [comment]
Yes, I got this part. Thank you for helping me out.

**Comment by dvblogic** [comment]
By the way, is my understanding correct that master does not need a tag? It always takes whatever is the latest?

**Comment by ksooo** [comment]
Correct. At least this is how it currently works.

**Comment by dvblogic** [comment]
@ksooo big thanks on helping me out!

**Comment by ksooo** [comment]
you're welcome.

**Pull request merged**
