### PR TITLE
Add PVR addon update interval setting

### PR DESCRIPTION
**Pull request by linknetx**
This adds a setting to the PVR addon to enable the update interval to be changed from the present fixed value of 5 minutes to a range of values from 1 to 60 minutes.

The current update interval fixed value of 5 minutes may have been originally set to this high value to reduce network traffic but for a modern high speed LAN this is far too long. A value of 1 minute in testing removes the long update delays and seems to be the optimum value.

Edit: 
The feedback suggests that some users think the opposite and that 5 minutes is too frequent and a waste of network resources so the setting now has a maximum value of 60 minutes. 

The setting still defaults to the original 5 minutes but then enables it to be changed in 1 minute steps from 1 to 10 minutes and then in 10 minute steps to a maximum of 60 minutes.

update interval

### CODE REVIEW

**Comment by ksooo** [comment]
This PR does not make to much sense as  Kodi already has an advanced setting to adjust this value. Additionaly, there is an open pr for Kodi, that increases the default for this value to 2 hours. I expect that pr to be merged today or tomorrow

**Comment by ksooo** [comment]
Wait, you seem to want the opposite of what others want. Their argument is that  updating every 5 minutes is far to often as this is a massive waste of network resources... Hahaha, I love contradicting requirements...

**Comment by ksooo** [comment]
However, the update interval is not fixed to  5 mins, you can ofc also reduce the value using another advanced setting.

So, no point in your PR, imo.

**Comment by ksooo** [comment]
To make confusion perfect, the  afvsnced setting I was talking about in my first comment is another one as the one in my previous comment.

Refer to Kodi wiki for documentation on  advanced settings.

**Comment by linknetx** [comment]
Now I'm confused, the only setting that I can see that can be changed in the advanced settings is the guide update interval.

This is for the addon update interval, so if users want more than 5 minutes this is easy to include in this.

**Comment by ksooo** [comment]
I was assuming we're  talking about EPG update internal, no?

**Comment by linknetx** [comment]
This has nothing to do with the EPG update interval, it is the update interval that the pvr addon uses to update the timer and recording info.

**Comment by linknetx** [comment]
Changed the range of settings for the update interval to 1 to 60 minutes in consideration of the feedback received.

**Comment by ksooo** [comment]
Some people consider more than  2 hours the only acceptable interval, at least for  EPG...

**Comment by linknetx** [comment]
> Some people consider more than 2 hours the only acceptable interval, at least for EPG...

Yes, that's fine since the EPG is updated by some of the service providers only on a daily basis, so 2 hours is probably too frequent.

However once a recording is finished, for example, it's nice to have the recording list updated to reflect that within a reasonable time. That's what this attempts to address. There's substantially less data involved in the timers and recordings update than that involved in updating the EPG so it can afford to be reasonably frequent.

**Comment by ksooo** [comment]
> However once a recording is finished, for example, it's nice to have the recording list updated to reflect that within a reasonable time. That's what this attempts to address. There's substantially less data involved in the timers and recordings update than that involved in updating the EPG so it can afford to be reasonably frequent.

 Fair enough.

**Comment by linknetx** [comment]
Giving this more thought I think that extending the range of settings for the update interval as far as 1 to 15 minutes has it's drawbacks and a range of 1 to 10 would be more sensible.  Many programs are around 10 minutes long, for example news broadcasts and many children's programs, and with the update interval set at 15 minutes the 'recording started' and 'recording completed' messages may well coincide. A user might think that the recording was started and then cancelled immediately afterwards.

**Comment by linknetx** [comment]
@dvblogic 

Could you please let me know if this is being considered for inclusion.

Thanks.

**Comment by linknetx** [comment]
Excellent news. Thanks.

**Pull request merged**
