### PR TITLE
[Matrix/Nexus] copyright year increase, depends update and cleanup

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by samnazarko** [comment]
The TinyXML2 update could break building on older systems, such as Debian Buster because the CMake version is too old. On Buster, we get:

>CMake 3.15 or higher is required.  You are running version 3.13.4

I've mentioned this in Slack.

**Comment by phunkyfish** [comment]
> The TinyXML2 update could break building on older systems, such as Debian Buster because the CMake version is too old. On Buster, we get:
> 
> > CMake 3.15 or higher is required.  You are running version 3.13.4
> 
> I've mentioned this in Slack.

Next PVR already uses tiny xml 2. Does that have the same problem?

**Comment by samnazarko** [comment]
No - the other PVR add-one still depend on TinyXML 2.6.2 and it works fine. I’m not sure it makes sense for us to depend on and build two different versions across binary add-ons.

Maybe the newer TinyXML should be postponed for Kodi 20 and be applied to all addons?

**Comment by phunkyfish** [comment]
Leaving tinyxml2 for Nexus make sense to me. What do you think @AlwinEsch ?

**Comment by AlwinEsch** [comment]
Yes, I will then revert the commit to Matrix and bring it into Nexus only.

Regarding the old TinyXML (2.6.2_2), I will look to Nexus to remove on following addons as well:
- pvr.njoy
- pvr.mediaportal.tvserver
- pvr.vuplus
- pvr.dvbviewer
- pvr.rtl.radiofm

Doesn't like to be dependent on dependencies which are not continued in development and then maybe unexpectedly stop creation with C++ language changes or new OS.

**Pull request merged**
